### ISSUE TITLE
Use pym.js for responsive iframes

### ISSUE THREAD

**Issue by beamalsky** [beamalsky/medical-examiner-data#50]
c/o @pjsier

**Comment by pjsier** [comment]
@beamalsky would it be useful for me to put in a PR for this? Here's an example of using it on another Gatsby project, and I think it would be pretty straightforward here

https://github.com/City-Bureau/chi-covid-resources/blob/3cea258e64e49e90b845aa4c596f310857273e9e/src/pages/embed.js#L61-L70

**Comment by beamalsky** [comment]
If you feel like you have time that'd be great!
